-- RECONSTRUCTED baseline: the tables that existed before supabase/migrations/20260408_enable_rls.sql.
--
-- These tables were originally created in the Supabase dashboard, so no migration holds their
-- DDL. This file is rebuilt from the column names src/App.jsx reads and writes. It is good
-- enough to prove the security policies port to plain Postgres, but it is NOT the source of
-- truth for column types, defaults or indexes.
-- Before any real AWS cutover, replace this file with a schema-only dump of production
-- (pg_dump --schema-only) and re-run the local test suite against it.

CREATE TABLE IF NOT EXISTS public.practices (
  id         text PRIMARY KEY,
  name       text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.tc_users (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  auth_user_id uuid,
  name         text,
  email        text,
  role         text NOT NULL DEFAULT 'tc',
  status       text NOT NULL DEFAULT 'active',
  practice_id  text REFERENCES public.practices(id),
  created_at   timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.patients (
  id                   text PRIMARY KEY,
  name                 text,
  phone                text DEFAULT '',
  age                  text,
  npe_date             text,
  location             text,
  dp                   text,
  contract_amount      text DEFAULT '',
  tc                   text DEFAULT '',
  br boolean DEFAULT false, inv boolean DEFAULT false, ph1 boolean DEFAULT false,
  ph2 boolean DEFAULT false, ltd boolean DEFAULT false, r_plus boolean DEFAULT false,
  w_plus boolean DEFAULT false, pif boolean DEFAULT false,
  st boolean DEFAULT false, sch boolean DEFAULT false, pen boolean DEFAULT false,
  obs boolean DEFAULT false, mp boolean DEFAULT false, notx boolean DEFAULT false,
  dbrets boolean DEFAULT false,
  obstacle             text DEFAULT '',
  notes                text DEFAULT '',
  bond_date            text DEFAULT '',
  start_date           text DEFAULT '',
  contact_attempts     integer DEFAULT 0,
  next_touch_date      text,
  last_contact_date    text,
  contact_log          jsonb DEFAULT '[]'::jsonb,
  from_pending         boolean DEFAULT false,
  insurance_workflow   jsonb,
  practice_id          text REFERENCES public.practices(id),
  created_at           timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.feedback (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  practice_id text,
  tc_name     text,
  tc_email    text,
  view        text,
  category    text,
  description text,
  status      text DEFAULT 'open',
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.settings (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key         text NOT NULL,
  value       jsonb,
  practice_id text,
  UNIQUE (key, practice_id)
);

CREATE TABLE IF NOT EXISTS public.practice_metrics (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  year            integer NOT NULL,
  month           integer NOT NULL,
  practice_id     text,
  net_production  numeric, collections numeric,
  npe_scheduled   integer, npe_showed integer, obs_added integer, starts integer,
  show_up_rate    numeric, conversion_rate numeric, avg_case_fee numeric,
  notes           text,
  updated_at      timestamptz DEFAULT now(),
  UNIQUE (year, month, practice_id)
);

CREATE TABLE IF NOT EXISTS public.practice_goals (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  year              integer NOT NULL,
  month             integer NOT NULL,
  practice_id       text,
  production_goal   numeric DEFAULT 0,
  start_goal        numeric DEFAULT 0,
  npe_goal          numeric DEFAULT 0,
  conversion_goal   numeric DEFAULT 0,
  avg_case_fee_goal numeric DEFAULT 0,
  UNIQUE (year, month, practice_id)
);
