import { achFeeCents, money, surchargeCents, MAX_LOCATIONS } from './workflow.mjs';

const safe = value => String(value || '').replace(/[<>&"']/g, c => ({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&#039;'}[c]));
const section = (title, body) => `<h2>${title}</h2><p>${body}</p>`;
// v1 was approved by counsel word for word on 2026-10-07. v2 (same day) only changes the card
// sentences: cards with no surcharge until a state is cleared for it. Any change to the agreement
// text must get a new version so earlier signatures stay tied to what was signed.
export const AGREEMENT_VERSION = '2026-10-07-v2';

// The provider named in every agreement (the contracting party; "CadenceIQ" is the product
// name, not a registered fictitious name).
export const COMPANY = {
  legalName: 'Miller Orthodontics Technology LLC',
  formationState: 'Florida',
  address: '1303 W Fletcher Ave, Tampa, FL 33612',
  noticeEmail: 'drzack@northtampabraces.com',
  venueCounty: 'Hillsborough',
};

export function documentPackage(onboarding) {
  const d=onboarding.details||{}, p=onboarding.plan||{};
  const effective=onboarding.signedAt?new Date(onboarding.signedAt).toLocaleDateString():'the date Customer signs electronically';
  const monthly=Number(p.monthlyFeeCents)||0, setup=Number(p.setupFeeCents)||0;
  const achMonthly=achFeeCents(monthly), achSetup=achFeeCents(setup);
  const cardMonthly=surchargeCents(monthly), cardSetup=surchargeCents(setup);
  // The card surcharge applies only where the practice's state is cleared for it.
  const surcharged=(Number(onboarding.cardSurchargeBps)||0)>0;
  const cardTerms=surcharged
    ?`If Customer pays by credit card, a separately disclosed surcharge applies equal to Provider’s card processing cost (2.9% plus $0.30 per charge) and never more than 3% of the charge: currently ${money(cardSetup)} on the implementation fee and ${money(cardMonthly)} monthly. Debit and prepaid cards are not accepted for card payment.`
    :`Customer may pay by credit or debit card with no surcharge. Where permitted by law, Provider may later apply a separately disclosed credit-card surcharge, equal to its card processing cost (2.9% plus $0.30 per charge) and never more than 3% of the charge, on at least 30 days’ written notice; Customer may switch to bank account (ACH) payment at any time.`;
  const provider=`${safe(COMPANY.legalName)}, a ${safe(COMPANY.formationState)} limited liability company`;
  const customer=safe(d.legalName), notice=safe(COMPANY.noticeEmail), address=safe(COMPANY.address);
  const cancellation=`Customer may cancel at any time by written notice emailed to ${notice}. Cancellation takes effect at the end of the first billing month that ends at least 30 days after Provider receives the notice, and fees for every billing month that begins before that date remain due. Provider may likewise end the subscription on at least 30 days’ written notice. Provider will confirm each cancellation by email.`;
  return [
    {id:'order-form',title:'Order Form',body:`<h1>CadenceIQ Order Form</h1><p><strong>Provider:</strong> ${provider} (“Provider”), ${address}<br><strong>Customer:</strong> ${customer}<br><strong>Customer address:</strong> ${safe(d.officeAddress)}, ${safe(d.city)}, ${safe(d.state)} ${safe(d.postalCode)}<br><strong>Authorized signer:</strong> ${safe(d.signerName)}, ${safe(d.signerTitle)}<br><strong>Billing email:</strong> ${safe(d.billingEmail)}<br><strong>Locations:</strong> ${safe((d.locations||[]).join(', '))}<br><strong>Plan:</strong> ${safe(p.name)}<br><strong>Effective date:</strong> ${safe(effective)}</p>
      ${section('1. Services and implementation','Subscription access to the CadenceIQ software’s practice-intelligence, workflow, reporting, and patient follow-up features for the listed locations, plus standard onboarding and support. Customer will timely provide accurate configuration, user, location, source-system, and integration information. Custom development, data cleanup, on-site work, or third-party services require a separate written order.')}
      ${section('2. Fees',`One-time implementation fee: <strong>${money(setup)}</strong>, which is non-refundable once this Order Form is signed. Monthly subscription: <strong>${money(monthly)}</strong>, billed monthly in advance. Pricing is per practice: one legal entity operating under one federal tax identification number, with up to ${MAX_LOCATIONS} office locations. Additional locations or entities require a separate or custom Order Form.${p.key==='foundation'?' As a Foundation Partner, Customer keeps this monthly rate so long as Customer’s subscription remains continuously in effect; the rate ends if the subscription is canceled, lapses, or is terminated for nonpayment. While the rate is in effect, the renewal price-change terms of the MSA do not apply to it.':''} ${cardTerms} If Customer pays by bank account (ACH), a separately disclosed processing-cost recovery amount applies, based on the processor’s 0.8% ACH fee and capped at $5 per debit: currently ${money(achSetup)} on the implementation fee and ${money(achMonthly)} monthly. Customer is responsible for applicable transaction taxes, excluding taxes on Provider’s net income.`)}
      ${section('3. Term, renewal, and cancellation',`The initial term is one month and automatically renews for successive one-month periods until canceled. ${cancellation} Cancellation stops future renewals but does not reverse earned fees or charges already submitted.`)}
      ${section('4. Incorporated terms and priority','This Order Form, the Master Services Agreement (“MSA”), the Business Associate Agreement (“BAA”), and the Recurring Payment Authorization form one Agreement. The BAA controls for PHI; this Order Form controls commercial terms; the MSA controls all other matters.')}
      ${section('5. Formation and approval','This Agreement becomes effective when Customer signs electronically (the “Effective Date”) and is accepted by Provider when it activates Customer’s account after the first payment succeeds; Provider’s signature is not required. By signing electronically, Customer confirms that its identity, locations, fees, renewal terms, payment-method costs, and cancellation terms are accurate, were clearly disclosed, and are accepted. Special terms are effective only if in a writing signed by both parties.')}`},

    {id:'msa',title:'Master Services Agreement',body:`<h1>Master Services Agreement</h1><p>This MSA is between ${provider} (“Provider”) and ${customer} (“Customer”), effective ${safe(effective)}.</p>
      ${section('1. Agreement structure','Order Forms identify subscriptions, locations, fees, and special terms. The “service” means Provider’s hosted CadenceIQ software and related onboarding and support. Customer purchase-order terms do not amend the Agreement. “Customer Data” means data Customer or its users submit to the service or that the service receives from Customer’s systems on Customer’s behalf, including PHI.')}
      ${section('2. Service and license','During an active subscription, Provider grants Customer a limited, nonexclusive, nontransferable right for authorized workforce members and contractors to use the hosted service for Customer’s internal operations. Customer is responsible for its users’ compliance with the Agreement. Provider may improve the service without materially reducing paid core functionality during a term.')}
      ${section('3. Restrictions','Customer will not resell, sublicense, reverse engineer, scrape, probe, bypass security, introduce malicious code, permit unauthorized access, use the service unlawfully, or use it to build a competing product. Customer will not place payment-card numbers, passwords, or unnecessary sensitive information in free-text fields.')}
      ${section('4. Customer responsibilities','Customer controls its accounts and data, determines lawful purposes and permissions, provides accurate information, configures least-privilege access, trains users, promptly removes departed users, protects devices and credentials, and maintains source-system backups. Customer is responsible for clinical, employment, billing, coding, reimbursement, and business decisions. Provider does not provide medical, legal, accounting, coding, or reimbursement advice.')}
      ${section('5. Implementation, integrations, and third parties','Timelines are estimates and depend on Customer cooperation. Integrations rely on third-party systems, APIs, formats, and availability outside Provider’s control. Customer represents that it is authorized under its agreements with its practice-management and other source-system vendors to grant Provider the access Customer configures, and Customer is responsible for keeping those credentials current. Provider is not responsible for third-party changes, outages, inaccurate source data, or third-party terms. Added work caused by scope changes, delay, or inaccurate data may require a change order.')}
      ${section('6. Fees, invoices, and taxes','Fees are due under the Order Form and are non-refundable except as expressly stated in the Agreement or required by law. Customer must dispute an invoice in reasonable detail within 30 days. Undisputed overdue amounts may accrue interest at the lesser of 1.5% monthly or the lawful maximum, plus reasonable collection costs. Provider may change renewal pricing on at least 30 days’ advance written notice, effective at a later renewal, except as an Order Form provides otherwise.')}
      ${section('7. Renewal and cancellation',`The MSA continues while an Order Form is active. Monthly subscriptions auto-renew as disclosed in the Order Form. ${cancellation}`)}
      ${section('8. Suspension','Provider may suspend affected access for overdue fees, a security threat, unlawful use, material breach, or emergency maintenance. When practicable it will give notice and an opportunity to cure, and will limit suspension to the affected scope. Suspension does not waive amounts owed.')}
      ${section('9. Customer Data and privacy','Customer owns Customer Data. Customer instructs Provider to host, copy, transmit, transform, and otherwise process it only to provide, secure, maintain, and support the service or as required by law. The BAA governs PHI. Provider will not sell Customer Data. Provider may create information de-identified in accordance with applicable law (for PHI, 45 C.F.R. § 164.514(a)–(c), as permitted by the BAA) that does not identify Customer or any individual, and may use it for security, analytics, benchmarking, and service improvement.')}
      ${section('10. Security','Provider will maintain a written security program with reasonable administrative, physical, and technical safeguards appropriate to the service and data, including access controls, authentication, logging, encryption in transit and at rest where appropriate, vulnerability management, backups, incident response, and workforce training. Customer Data is stored and processed in the United States. No system is completely secure, and Provider does not warrant that every attack will be prevented.')}
      ${section('11. Confidentiality','Each recipient will use the other party’s nonpublic information only for the Agreement, protect it with at least reasonable care, and disclose it only to personnel and contractors with a need to know and confidentiality duties. Exclusions apply to information lawfully known without restriction, independently developed, publicly available without breach, or lawfully received from another source. Required disclosures are permitted after advance notice when legally allowed. These duties last for the term and three years after it, and for trade secrets and Customer Data for as long as they remain protected.')}
      ${section('12. Intellectual property and feedback','Provider and its licensors own the service, software, documentation, methods, and improvements. Customer receives only the express license. Provider may use voluntary feedback without identifying Customer or disclosing Customer Confidential Information.')}
      ${section('13. Compliance','Each party will comply with laws applicable to its performance. Customer is responsible for required notices, consents, lawful bases, policies, and records for its data collection and use, including any patient consent required to contact patients by phone, text message, or email through or based on the service (for example, under the Telephone Consumer Protection Act). Neither party may use the service for unlawful discrimination, deception, or prohibited decisions.')}
      ${section('14. Warranties and disclaimers','Each party warrants its authority to enter the Agreement. Provider warrants that the service will materially conform to its documentation under normal use and that services will be performed in a professional manner. The exclusive remedy for breach of this warranty is correction, re-performance, or, if Provider cannot cure a material breach, termination and a prorated refund of prepaid unused subscription fees. <strong>EXCEPT AS EXPRESSLY STATED IN THIS SECTION, THE SERVICE IS PROVIDED “AS IS,” AND EACH PARTY DISCLAIMS ALL IMPLIED WARRANTIES, INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT, TO THE MAXIMUM EXTENT PERMITTED BY LAW.</strong>')}
      ${section('15. Indemnification','Subject to Section 16, Provider will defend a third-party claim that the unmodified service infringes a United States patent, copyright, or trademark and pay finally awarded damages or approved settlements, subject to prompt notice and defense control. Provider may modify, replace, or terminate the affected service and refund prepaid unused fees. This excludes Customer Data, unauthorized combinations, Customer instructions, and unauthorized use. Subject to Section 16, Customer will defend claims arising from Customer Data, unlawful or unauthorized use, or breach of Sections 3, 4, 5, or 13 under the same procedures.')}
      ${section('16. Limitation of liability','<strong>(a) NEITHER PARTY IS LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, PUNITIVE, OR CONSEQUENTIAL DAMAGES, OR FOR LOST PROFITS, REVENUE, GOODWILL, OR DATA. (b) GENERAL CAP: EACH PARTY’S AGGREGATE LIABILITY ARISING OUT OF THE AGREEMENT WILL NOT EXCEED THE GREATER OF (i) THE FEES PAID AND PAYABLE BY CUSTOMER IN THE 12 MONTHS BEFORE THE EVENT GIVING RISE TO THE CLAIM AND (ii) $25,000. (c) ENHANCED CAP: FOR CLAIMS ARISING FROM A BREACH OF SECTION 10, OF SECTION 11 AS IT RELATES TO CUSTOMER DATA, OR OF THE BAA, AND FOR EACH PARTY’S OBLIGATIONS UNDER SECTION 15, EACH PARTY’S AGGREGATE LIABILITY WILL NOT EXCEED THE GREATER OF $100,000 AND THE LIMITS OF THE CYBER LIABILITY OR TECHNOLOGY ERRORS-AND-OMISSIONS INSURANCE PROVIDER THEN MAINTAINS; AMOUNTS PAID UNDER THIS CAP DO NOT REDUCE THE GENERAL CAP. (d) THESE LIMITS DO NOT APPLY TO CUSTOMER’S PAYMENT OBLIGATIONS, A PARTY’S FRAUD OR WILLFUL MISCONDUCT, OR LIABILITY THAT CANNOT LAWFULLY BE LIMITED.</strong>')}
      ${section('17. Termination and data transition','Either party may terminate an affected Order Form for material breach not cured within 30 days after notice; the cure period is 10 days for nonpayment, and no cure period applies to an incurable breach. Customer may request an export of its Customer Data in CSV format within 30 days after termination. Provider may then delete remaining data under its retention schedule, except legally required copies and protected backups, which remain protected until deleted in the ordinary course.')}
      ${section('18. Force majeure','Neither party is liable for delay caused by events beyond reasonable control, excluding payment duties. The affected party will mitigate and resume performance. Either party may terminate an affected service if a material event continues more than 60 days.')}
      ${section('19. Notices and assignment',`Notices of cancellation and routine operational notices may be given by email. Other legal notices must be in writing and sent by email plus recognized courier to the addresses in the Order Form; notices to Provider go to ${notice} and ${address}. Neither party may assign without consent except to an affiliate or in a merger, reorganization, or sale of substantially all relevant assets if the assignee assumes the Agreement and is not a direct competitor of the other party.`)}
      ${section('20. General',`The parties are independent contractors; no third party is a beneficiary. Unenforceable provisions will be narrowed and the remainder survives. Waivers must be written. Sections 6 (as to amounts owed), 9, 11, 12, 15, 16, 17, 19, and 20, and the BAA’s provisions on PHI disposition, survive termination. Florida law governs, and exclusive venue lies in the state courts of ${safe(COMPANY.venueCounty)} County, Florida, or the federal court for that district. In any action to enforce the Agreement, the prevailing party may recover its reasonable attorneys’ fees and costs. The Agreement is the parties’ entire agreement on its subject and may be amended only by a writing signed by both parties. Electronic signatures and counterparts are effective. Provider may identify Customer by name as a client in customer lists and sales materials; Customer may opt out at any time by email to ${notice}.`)}`},

    {id:'baa',title:'Business Associate Agreement',body:`<h1>Business Associate Agreement</h1><p>This BAA is between ${customer} (“Covered Entity”) and ${provider} (“Business Associate”), effective ${safe(effective)}, and supplements the MSA.</p>
      ${section('1. Definitions','“Breach,” “Designated Record Set,” “ePHI,” “Individual,” “Minimum Necessary,” “PHI,” “Required by Law,” “Secretary,” “Security Incident,” “Subcontractor,” “Unsecured PHI,” “Use,” and “Disclosure” have the meanings in 45 C.F.R. Parts 160 and 164 (the “HIPAA Rules”).')}
      ${section('2. Permitted uses and disclosures','Business Associate may use or disclose PHI only to perform the services, as permitted by this BAA, or as Required by Law. It may use PHI for its proper management, administration, or legal responsibilities, and disclose PHI for those purposes only when the disclosure is Required by Law or the recipient gives reasonable assurances of confidentiality and breach reporting. Business Associate may de-identify PHI in accordance with 45 C.F.R. § 164.514(a)–(c) and may use and disclose the resulting de-identified information for any lawful purpose. Data aggregation for Covered Entity’s health care operations requires Covered Entity’s express written authorization. Business Associate will not sell PHI, use it for marketing, or use or disclose it in a way that would violate the HIPAA Rules if done by Covered Entity, except as permitted for a business associate.')}
      ${section('3. Safeguards and minimum necessary','Business Associate will use appropriate safeguards, comply with the applicable requirements of 45 C.F.R. Part 164, Subpart C for ePHI, and limit uses, disclosures, and requests to the Minimum Necessary. PHI is stored and processed only in the United States.')}
      ${section('4. Reporting and response','Business Associate will report an impermissible use or disclosure, Breach of Unsecured PHI, or material Security Incident without unreasonable delay and, where practicable, within 10 business days after discovery, and in no case later than required by the HIPAA Rules. It will provide the information available to it that Covered Entity needs for its notification duties, including the identity of affected Individuals where known; investigate; mitigate known harmful effects; preserve evidence; and reasonably cooperate with notices and inquiries, including those required by state breach-notification laws such as Fla. Stat. § 501.171. Routine unsuccessful security attempts that cause no unauthorized access, use, disclosure, modification, or destruction are deemed reported in aggregate unless law or a written agreement requires individual notice.')}
      ${section('5. Subcontractors','Each Subcontractor that creates, receives, maintains, or transmits PHI on Business Associate’s behalf must agree in writing to restrictions, safeguards, and conditions at least as protective as those applicable to Business Associate, including applicable Security Rule duties. Business Associate will identify its Subcontractors that handle PHI on request.')}
      ${section('6. Individual rights and records','If Business Associate maintains PHI in a Designated Record Set, it will make PHI available for access and amendment, provide information for an accounting of disclosures, and incorporate amendments as required by 45 C.F.R. §§ 164.524, 164.526, and 164.528. Requests received directly from Individuals will be forwarded to Covered Entity unless Business Associate is legally required to respond.')}
      ${section('7. Covered Entity duties','Covered Entity will notify Business Associate of relevant limitations in its Notice of Privacy Practices, permission changes or revocations, and agreed restrictions. Covered Entity will not request a use or disclosure that would violate the HIPAA Rules if made by Covered Entity, except as permitted for a business associate.')}
      ${section('8. Government access and delegated duties','Business Associate will make its internal practices, books, and records relating to PHI available to the Secretary to determine HIPAA compliance. When it carries out a Covered Entity obligation under the Privacy Rule, it will comply with the requirements that apply to that obligation.')}
      ${section('9. Term, termination, and PHI disposition','This BAA takes effect on the Effective Date and remains in effect while Business Associate creates, receives, maintains, or transmits PHI for Covered Entity. Covered Entity may terminate affected services if Business Associate materially violates this BAA and fails to cure within a reasonable period specified by Covered Entity, or immediately if cure is not possible. At termination, Business Associate will return or destroy PHI if feasible. If that is infeasible, it will extend these protections to the retained PHI, limit further use and disclosure to the purposes that make return or destruction infeasible, and securely destroy it when feasible. This Section survives termination.')}
      ${section('10. Interpretation and priority','This BAA is interpreted to permit compliance with HIPAA, HITECH, and the HIPAA Rules as amended. Amendments required by changes in those laws apply automatically. This BAA controls any conflict concerning PHI. Where an applicable state privacy or breach-notification law is more protective of PHI, the parties will comply with it.')}`},

    {id:'payment-authorization',title:'Recurring Payment Authorization',body:`<h1>Recurring Payment and ACH Authorization</h1><p><strong>Customer:</strong> ${customer}<br><strong>Billing email:</strong> ${safe(d.billingEmail)}<br><strong>Provider:</strong> ${provider}</p>
      ${section('1. Recurring authorization','Customer authorizes Provider and its payment processor to charge the payment method Customer provides in the secure checkout for the implementation fee, the monthly subscription, the separately disclosed payment-method processing cost, applicable taxes, and other amounts expressly authorized by the Agreement. Monthly charges occur on or about the same calendar day as the initial subscription charge until the subscription ends under the cancellation terms below.')}
      ${section('2. Amounts and costs',`Current base amounts are ${money(setup)} for implementation (non-refundable) and ${money(monthly)} monthly. ${surcharged?`If paying by credit card, the surcharge equal to Provider’s card processing cost (2.9% plus $0.30, never more than 3%) is currently ${money(cardSetup)} on implementation and ${money(cardMonthly)} monthly.`:'Card payments currently carry no surcharge; any future surcharge requires at least 30 days’ written notice.'} If paying by bank account (ACH), the processing-cost recovery amount, based on the processor’s 0.8% fee and capped at $5 per debit, is currently ${money(achSetup)} on implementation and ${money(achMonthly)} monthly. The exact total is shown before confirmation and on each invoice or receipt.`)}
      ${section('3. ACH authorization','If Customer selects ACH, it represents that the account is a business deposit account it is authorized to use, and it authorizes recurring electronic debits and any necessary correcting credits. ACH payments may take several business days to settle, and account activation may wait until payment succeeds. This authorization remains in effect until revoked as described below.')}
      ${section('4. Variable amounts and notice','Amounts may vary because of taxes, approved service changes, processing costs, credits, failed-payment costs, or renewal pricing. Provider will give any legally required advance notice of material price changes. Customer agrees that the invoice or checkout disclosure provided before or at the time of a charge constitutes notice of its amount and date, to the extent payment-network rules permit.')}
      ${section('5. Failed payments and disputes','Provider may retry failed payments as permitted. Customer will reimburse a failed-ACH or ACH-dispute fee only to the extent actually charged by the processor (currently $4 for a failed debit and $15 for a dispute), plus any lawful bank-return charge disclosed before collection. No fee applies when a failure resulted from Provider’s error. Disputing a valid charge does not cancel the subscription.')}
      ${section('6. Cancellation and revocation',`${cancellation} Separately, Customer may revoke this authorization by written notice to ${notice} received at least three business days before a scheduled debit. Revoking this authorization does not cancel the subscription or relieve Customer of amounts owed through the cancellation effective date, and Customer must then provide another accepted payment method. Revocation does not affect completed transactions or a debit already submitted. Provider will confirm cancellation or revocation by email.`)}
      ${section('7. Payment information and consent record','Provider does not receive or store the full card or bank-account number entered in the secure checkout. Customer authorizes tokenized storage of its payment method by the processor, may print or save a copy of this authorization before signing, and may request an emailed copy at any time. Customer consents to sign electronically and represents that the signer is authorized to bind Customer.')}`}
  ];
}

export function printablePackage(onboarding) {
  const docs=documentPackage(onboarding);
  return `<!doctype html><html><head><meta charset="utf-8"><title>CadenceIQ Agreement Package</title><style>body{font:14px/1.55 Arial,sans-serif;color:#172033;max-width:800px;margin:40px auto;padding:0 24px}h1{font-size:24px}h2{font-size:16px;margin-top:22px}.doc{page-break-after:always}.ver{font-size:12px;color:#64748b}.sig{margin-top:40px;border-top:1px solid #999;padding-top:16px}</style></head><body><div class="ver">Agreement version ${AGREEMENT_VERSION}</div>${docs.map(x=>`<section class="doc">${x.body}</section>`).join('')}<section class="sig"><strong>Electronic signature:</strong> ${safe(onboarding.signatureName||'Not signed')}<br><strong>Title:</strong> ${safe(onboarding.details?.signerTitle)}<br><strong>Date:</strong> ${safe(onboarding.signedAt||'')}<br><strong>Agreement version:</strong> ${AGREEMENT_VERSION}</section></body></html>`;
}
