import { achFeeCents, money, surchargeCents } from './workflow.mjs';

const safe = value => String(value || '').replace(/[<>&"']/g, c => ({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&#039;'}[c]));
const section = (title, body) => `<h2>${title}</h2><p>${body}</p>`;
export const AGREEMENT_VERSION = 'draft-2026-10-05-v3';

export function documentPackage(onboarding) {
  const d=onboarding.details||{}, p=onboarding.plan||{}, c=onboarding.company||{};
  const effective=onboarding.signedAt?new Date(onboarding.signedAt).toLocaleDateString():'the date of the final signature';
  const monthly=Number(p.monthlyFeeCents)||0, setup=Number(p.setupFeeCents)||0;
  const achMonthly=achFeeCents(monthly,onboarding.achFeeBps||80,onboarding.achFeeCapCents||500);
  const achSetup=achFeeCents(setup,onboarding.achFeeBps||80,onboarding.achFeeCapCents||500);
  const cardMonthly=surchargeCents(monthly,onboarding.cardSurchargeBps||300), cardSetup=surchargeCents(setup,onboarding.cardSurchargeBps||300);
  const cadence=safe(c.legalName||'CadenceIQ LLC'), customer=safe(d.legalName), notice=safe(c.noticeEmail||'[CADENCE NOTICE EMAIL]');
  return [
    {id:'order-form',title:'Order Form',body:`<h1>CadenceIQ Order Form</h1><p><strong>Provider:</strong> ${cadence}<br><strong>Customer:</strong> ${customer}<br><strong>Address:</strong> ${safe(d.officeAddress)}, ${safe(d.city)}, ${safe(d.state)} ${safe(d.postalCode)}<br><strong>Authorized signer:</strong> ${safe(d.signerName)}, ${safe(d.signerTitle)}<br><strong>Billing email:</strong> ${safe(d.billingEmail)}<br><strong>Locations:</strong> ${safe((d.locations||[]).join(', '))}<br><strong>Plan:</strong> ${safe(p.name)}<br><strong>Effective date:</strong> ${safe(effective)}</p>
      ${section('1. Services and implementation','Subscription access to CadenceIQ’s practice-intelligence, workflow, reporting, and patient follow-up features for the listed locations, plus standard onboarding and support. Customer will timely provide accurate configuration, user, location, source-system, and integration information. Custom development, data cleanup, on-site work, or third-party services require a separate written order.')}
      ${section('2. Fees',`One-time implementation: <strong>${money(setup)}</strong>. Monthly subscription: <strong>${money(monthly)}</strong> per practice (not per location), billed monthly in advance.${p.key==='foundation'?' As a Foundation Partner, Customer keeps this monthly rate for as long as Customer remains an active client; the renewal price-change terms of the MSA do not apply to this rate.':''} If legally permitted and enabled, the separately disclosed 3% eligible credit-card surcharge is ${money(cardSetup)} on implementation and ${money(cardMonthly)} monthly; debit and prepaid cards are excluded. ACH includes a separately disclosed processing-cost recovery amount based on the processor’s current 0.8% charge, capped at $5 per debit—currently ${money(achSetup)} on implementation and ${money(achMonthly)} monthly. Customer is responsible for applicable transaction taxes, excluding taxes on CadenceIQ’s net income.`)}
      ${section('3. Term, renewal, and cancellation','The initial term is one month and automatically renews for successive one-month periods unless either party gives at least 30 days’ written notice of non-renewal. Cancellation stops future renewals but does not reverse earned fees or charges already submitted.')}
      ${section('4. Incorporated terms and priority','This Order Form, Master Services Agreement (“MSA”), Business Associate Agreement (“BAA”), and Recurring Payment Authorization are one Agreement. The BAA controls for PHI; this Order Form controls commercial terms; the MSA controls other matters.')}
      ${section('5. Approval','By signing electronically, Customer confirms that its identity, locations, fees, renewal terms, payment-method costs, and cancellation instructions are accurate, conspicuous, and accepted. Special terms are effective only if written and countersigned by both parties.')}`},

    {id:'msa',title:'Master Services Agreement',body:`<h1>Master Services Agreement</h1><p>This MSA is between ${cadence} (“CadenceIQ”) and ${customer} (“Customer”), effective ${safe(effective)}.</p>
      ${section('1. Agreement structure','Order Forms identify subscriptions, locations, fees, and special terms. Customer purchase-order terms do not amend the Agreement.')}
      ${section('2. Service and license','During an active subscription, CadenceIQ grants Customer a limited, nonexclusive, nontransferable right for authorized workforce members and contractors to use the hosted service for Customer’s internal operations. CadenceIQ may improve the service without materially reducing paid core functionality during a term.')}
      ${section('3. Restrictions','Customer will not resell, sublicense, reverse engineer, scrape, probe, bypass security, introduce malicious code, permit unauthorized access, use the service unlawfully, or use it to build a competing product. Customer will not place payment-card numbers, passwords, or unnecessary sensitive information in free-text fields.')}
      ${section('4. Customer responsibilities','Customer controls its accounts and data, determines lawful purposes and permissions, provides accurate information, configures least-privilege access, trains users, promptly removes departed users, protects devices and credentials, and maintains source-system backups. Customer is responsible for clinical, employment, billing, coding, reimbursement, and business decisions. CadenceIQ does not provide medical, legal, accounting, coding, or reimbursement advice.')}
      ${section('5. Implementation, integrations, and third parties','Timelines are estimates and depend on Customer cooperation. Integrations rely on third-party systems, APIs, formats, and availability outside CadenceIQ’s control. CadenceIQ is not responsible for third-party changes, outages, inaccurate source data, or third-party terms. Added work caused by scope changes, delay, or inaccurate data may require a change order.')}
      ${section('6. Fees, invoices, and taxes','Fees are due under the Order Form and non-refundable except as expressly stated or required by law. Customer must dispute an invoice in reasonable detail within 30 days. Undisputed overdue amounts may accrue interest at the lesser of 1.5% monthly or the lawful maximum, plus reasonable collection costs. CadenceIQ may change renewal pricing on at least 30 days’ advance notice, effective at a later renewal.')}
      ${section('7. Renewal and cancellation',`The MSA continues while an Order Form is active. Monthly subscriptions auto-renew as disclosed. Either party may prevent renewal with 30 days’ written notice. Customer may cancel through the billing portal or by notice to ${notice}. CadenceIQ will provide a reasonably accessible cancellation method and electronic confirmation.`)}
      ${section('8. Suspension','CadenceIQ may suspend affected access for overdue fees, a security threat, unlawful use, material breach, or emergency maintenance. When practicable it will give notice and an opportunity to cure, and will limit suspension to the affected scope. Suspension does not waive amounts owed.')}
      ${section('9. Customer Data and privacy','Customer owns Customer Data. Customer instructs CadenceIQ to host, copy, transmit, transform, and otherwise process it only to provide, secure, maintain, and support the service or as required by law. The BAA governs PHI. CadenceIQ will not sell Customer Data. CadenceIQ may use data de-identified under applicable law so it cannot reasonably identify Customer or an individual, solely for security, analytics, benchmarking, and service improvement.')}
      ${section('10. Security','CadenceIQ will maintain a written security program with reasonable administrative, physical, and technical safeguards appropriate to the service and data, including access controls, authentication, logging, encryption in transit and at rest where appropriate, vulnerability management, backups, incident response, and workforce training. No system is completely secure and prevention of every attack is not warranted.')}
      ${section('11. Confidentiality','Each recipient will use the other party’s nonpublic information only for the Agreement, protect it with at least reasonable care, and disclose it only to personnel and contractors with a need to know and confidentiality duties. Exclusions apply to information lawfully known without restriction, independently developed, publicly available without breach, or lawfully received from another source. Required disclosures are permitted after advance notice when legally allowed.')}
      ${section('12. Intellectual property and feedback','CadenceIQ and its licensors own the service, software, documentation, methods, and improvements. Customer receives only the express license. CadenceIQ may use voluntary feedback without identifying Customer or disclosing Customer Confidential Information.')}
      ${section('13. Compliance','Each party will comply with laws applicable to its performance. Customer is responsible for required notices, consents, lawful bases, policies, and records for its data collection and use. Neither party may use the service for unlawful discrimination, deception, or prohibited decisions.')}
      ${section('14. Warranties and disclaimers','Each party warrants authority to enter the Agreement. CadenceIQ warrants material conformity to documentation under normal use and professional performance of services. The exclusive remedy is correction, re-performance, or, if CadenceIQ cannot cure a material breach, termination and a prorated refund of prepaid unused subscription fees. Otherwise the service is provided “as is,” and implied warranties are disclaimed to the maximum extent allowed.')}
      ${section('15. Indemnification','CadenceIQ will defend a third-party claim that the unmodified service infringes a United States patent, copyright, or trademark and pay finally awarded damages or approved settlements, subject to prompt notice and defense control. CadenceIQ may modify, replace, or terminate the affected service and refund prepaid unused fees. This excludes Customer Data, unauthorized combinations, Customer instructions, and unauthorized use. Customer will defend claims arising from Customer Data, unlawful or unauthorized use, or breach of Sections 3, 4, or 13 under the same procedures.')}
      ${section('16. Liability','Neither party is liable for indirect, incidental, special, exemplary, punitive, or consequential damages or lost profits, revenue, goodwill, or data. Except for excluded claims, aggregate liability will not exceed fees paid or payable for the affected service during the preceding 12 months. The limits do not apply to payment duties, fraud, willful misconduct, indemnification, infringement or misappropriation of the other party’s intellectual property, or liability that cannot lawfully be limited. Counsel should decide whether confidentiality, security, and BAA claims require a separate enhanced cap.')}
      ${section('17. Termination and data transition','Either party may terminate an affected Order Form for material breach not cured within 30 days after notice; the cure period is 10 days for nonpayment, and no cure period applies to an incurable breach. Customer may request a standard data export within 30 days after termination if legally and technically feasible. CadenceIQ may then delete remaining data under its retention schedule, except legally required copies and protected backups, which remain protected until deleted.')}
      ${section('18. Force majeure','Neither party is liable for delay caused by events beyond reasonable control, excluding payment duties. The affected party will mitigate and resume performance. Either party may terminate an affected service if a material event continues more than 60 days.')}
      ${section('19. Notices and assignment',`Legal notices must be written and sent by email plus recognized courier to Order Form addresses; CadenceIQ notices go to ${notice}. Operational notices may be electronic. Neither party may assign without consent except to an affiliate or in a merger, reorganization, or sale of substantially all relevant assets if the assignee assumes the Agreement and is not a direct competitor of the other party.`)}
      ${section('20. General','The parties are independent contractors; no third party is a beneficiary. Unenforceable provisions will be narrowed and the remainder survives. Waivers must be written. Provisions intended by nature to survive will survive. Florida law governs, and exclusive venue will be in the state or federal courts in the Florida county of CadenceIQ’s principal office; counsel must complete the final county. The Agreement is complete and may be amended only by a signed writing, except expressly identified prospective policies. Electronic signatures and counterparts are effective.')}`},

    {id:'baa',title:'Business Associate Agreement',body:`<h1>Business Associate Agreement</h1><p>This BAA is between ${customer} (“Covered Entity”) and ${cadence} (“Business Associate”), effective ${safe(effective)}, and supplements the MSA.</p>
      ${section('1. Definitions','“Breach,” “Designated Record Set,” “ePHI,” “Individual,” “Minimum Necessary,” “PHI,” “Required by Law,” “Secretary,” “Security Incident,” “Subcontractor,” “Unsecured PHI,” “Use,” and “Disclosure” have the meanings in 45 C.F.R. Parts 160 and 164 (“HIPAA Rules”).')}
      ${section('2. Permitted uses and disclosures','Business Associate may use or disclose PHI only to perform the services, as permitted by this BAA, or as Required by Law. It may use PHI for proper management, administration, or legal responsibilities only when the disclosure is Required by Law or the recipient gives reasonable confidentiality and breach-reporting assurances. Data aggregation for Covered Entity’s health care operations requires express authorization. Business Associate will not sell PHI, use it for marketing, or use or disclose it in a way that would violate HIPAA if done by Covered Entity, except as permitted for a business associate.')}
      ${section('3. Safeguards and minimum necessary','Business Associate will use appropriate safeguards, comply with applicable requirements of 45 C.F.R. Part 164 Subpart C for ePHI, and limit uses, disclosures, and requests to the Minimum Necessary.')}
      ${section('4. Reporting and response','Business Associate will report an impermissible use or disclosure, Breach of Unsecured PHI, or material Security Incident without unreasonable delay and, where practicable, within 10 business days after discovery. It will provide available information needed for Covered Entity’s duties, investigate, mitigate known harmful effects, preserve evidence, and reasonably cooperate with notices and inquiries. Routine unsuccessful security attempts that cause no unauthorized access, use, disclosure, modification, or destruction are deemed reported in aggregate unless law or a written agreement requires individual notice.')}
      ${section('5. Subcontractors','Each Subcontractor that creates, receives, maintains, or transmits PHI must agree in writing to restrictions, safeguards, and conditions at least as protective as those applicable to Business Associate, including applicable Security Rule duties.')}
      ${section('6. Individual rights and records','If Business Associate maintains PHI in a Designated Record Set, it will make PHI available for access and amendment, provide information for an accounting of disclosures, and incorporate amendments as required by 45 C.F.R. §§ 164.524, 164.526, and 164.528. Direct Individual requests will be forwarded to Covered Entity unless Business Associate is legally required to respond.')}
      ${section('7. Covered Entity duties','Covered Entity will notify Business Associate of relevant limitations in its Notice of Privacy Practices, permission changes or revocations, and agreed restrictions. Covered Entity will not request a use or disclosure that would violate HIPAA if made by Covered Entity, except as permitted for a business associate.')}
      ${section('8. Government access and delegated duties','Business Associate will make internal practices, books, and records relating to PHI available to the Secretary to determine HIPAA compliance. When it carries out a Covered Entity Privacy Rule obligation, it will comply with requirements applicable to that obligation.')}
      ${section('9. Termination and PHI disposition','Covered Entity may terminate affected services if Business Associate materially violates this BAA and fails to cure in the specified reasonable period, or immediately if cure is impossible. At termination Business Associate will return or destroy PHI if feasible. If infeasible, it will extend these protections, limit further use and disclosure to the reason retention is necessary, and securely delete PHI when feasible.')}
      ${section('10. Interpretation and priority','This BAA is interpreted to permit compliance with HIPAA, HITECH, and amended regulations. Legally required regulatory amendments apply automatically. This BAA controls conflicts concerning PHI. More protective state privacy and breach laws may apply and must be evaluated by counsel for Customer’s jurisdictions.')}`},

    {id:'payment-authorization',title:'Recurring Payment Authorization',body:`<h1>Recurring Payment and ACH Authorization</h1><p><strong>Customer:</strong> ${customer}<br><strong>Billing email:</strong> ${safe(d.billingEmail)}<br><strong>Provider:</strong> ${cadence}</p>
      ${section('1. Recurring authorization','Customer authorizes CadenceIQ and its processor to charge the hosted-checkout payment method for the implementation fee, monthly subscription, separately disclosed payment-method processing cost, applicable taxes, and other amounts expressly authorized by the Agreement. Monthly charges occur on or about the same calendar day as the initial subscription charge until canceled.')}
      ${section('2. Amounts and costs',`Current base amounts are ${money(setup)} for implementation and ${money(monthly)} monthly. The eligible-credit-card 3% surcharge is currently ${money(cardSetup)} and ${money(cardMonthly)}. The ACH processing-cost recovery amount based on the processor’s current 0.8% fee, capped at $5 per debit, is currently ${money(achSetup)} and ${money(achMonthly)}. The exact total is shown before confirmation and on the invoice or receipt.`)}
      ${section('3. ACH authorization','If Customer selects ACH, it represents that the account is a business deposit account it is authorized to use and authorizes recurring electronic debits and necessary correcting credits. ACH may take several business days to settle, and access may remain pending until payment succeeds. This authorization remains effective until revoked below.')}
      ${section('4. Variable amounts and notice','Amounts may vary because of taxes, approved service changes, processing costs, credits, failed-payment costs, or renewal pricing. CadenceIQ will give legally required advance notice of material prospective price changes. Customer agrees that the invoice or electronic checkout disclosure provided before or at charge constitutes notice of amount and date to the extent payment-network rules permit.')}
      ${section('5. Failed payments and disputes','CadenceIQ may retry failed payments as permitted. Customer will reimburse a failed-ACH or ACH-dispute fee only to the extent actually charged by the processor—currently $4 for failure and $15 for dispute—plus a lawful bank-return charge disclosed before collection. No fee applies when failure resulted from CadenceIQ’s error. Disputing a valid charge does not cancel the subscription.')}
      ${section('6. Cancellation and revocation',`Customer may cancel renewals through the billing portal or written notice to ${notice}. To stop a scheduled ACH debit, revocation must arrive at least three business days beforehand unless law requires otherwise. Revocation does not affect completed transactions, amounts already owed, or a debit already submitted. CadenceIQ will confirm cancellation or revocation electronically.`)}
      ${section('7. Payment information and consent record','CadenceIQ does not receive or store the full card or bank-account number entered in hosted checkout. Customer authorizes tokenized storage by the processor, confirms it received a retainable copy of this authorization, consents electronically, and represents that the signer may bind Customer.')}`}
  ];
}

export function printablePackage(onboarding) {
  const docs=documentPackage(onboarding);
  return `<!doctype html><html><head><meta charset="utf-8"><title>CadenceIQ Agreement Package</title><style>body{font:14px/1.55 Arial,sans-serif;color:#172033;max-width:800px;margin:40px auto;padding:0 24px}h1{font-size:24px}h2{font-size:16px;margin-top:22px}.doc{page-break-after:always}.draft{padding:10px;border:2px solid #b45309;background:#fffbeb;color:#92400e;font-weight:700}.sig{margin-top:40px;border-top:1px solid #999;padding-top:16px}</style></head><body><div class="draft">DRAFT — requires review by licensed healthcare/SaaS counsel before production use. Version ${AGREEMENT_VERSION}</div>${docs.map(x=>`<section class="doc">${x.body}</section>`).join('')}<section class="sig"><strong>Electronic signature:</strong> ${safe(onboarding.signatureName||'Not signed')}<br><strong>Title:</strong> ${safe(onboarding.details?.signerTitle)}<br><strong>Date:</strong> ${safe(onboarding.signedAt||'')}<br><strong>Agreement version:</strong> ${AGREEMENT_VERSION}</section></body></html>`;
}
